// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
  user_id,
  job_id,
  notes
)
VALUES ($1, $2, $3)
RETURNING id, user_id, job_id, status, applied_at, updated_at, 
          interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
`

type CreateApplicationParams struct {
	UserID uuid.UUID      `json:"user_id"`
	JobID  uuid.UUID      `json:"job_id"`
	Notes  sql.NullString `json:"notes"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication, arg.UserID, arg.JobID, arg.Notes)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.InterviewDate,
		&i.OfferDate,
		&i.Notes,
		&i.SalaryOffer,
		&i.ReminderSent,
		&i.FollowUpDate,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.InterviewDate,
		&i.OfferDate,
		&i.Notes,
		&i.SalaryOffer,
		&i.ReminderSent,
		&i.FollowUpDate,
	)
	return i, err
}

const getApplicationByUserAndJob = `-- name: GetApplicationByUserAndJob :one
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE user_id = $1 AND job_id = $2
`

type GetApplicationByUserAndJobParams struct {
	UserID uuid.UUID `json:"user_id"`
	JobID  uuid.UUID `json:"job_id"`
}

func (q *Queries) GetApplicationByUserAndJob(ctx context.Context, arg GetApplicationByUserAndJobParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByUserAndJob, arg.UserID, arg.JobID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.InterviewDate,
		&i.OfferDate,
		&i.Notes,
		&i.SalaryOffer,
		&i.ReminderSent,
		&i.FollowUpDate,
	)
	return i, err
}

const getApplicationsByStatus = `-- name: GetApplicationsByStatus :many
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE user_id = $1 AND status = $2
ORDER BY applied_at DESC
`

type GetApplicationsByStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) GetApplicationsByStatus(ctx context.Context, arg GetApplicationsByStatusParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getApplicationsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.InterviewDate,
			&i.OfferDate,
			&i.Notes,
			&i.SalaryOffer,
			&i.ReminderSent,
			&i.FollowUpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobApplications = `-- name: GetJobApplications :many
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE job_id = $1
ORDER BY applied_at DESC
`

func (q *Queries) GetJobApplications(ctx context.Context, jobID uuid.UUID) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getJobApplications, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.InterviewDate,
			&i.OfferDate,
			&i.Notes,
			&i.SalaryOffer,
			&i.ReminderSent,
			&i.FollowUpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingReminders = `-- name: GetPendingReminders :many
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE reminder_sent = false
  AND interview_date IS NOT NULL
  AND interview_date <= NOW() + INTERVAL '24 hours'
  AND interview_date >= NOW()
`

func (q *Queries) GetPendingReminders(ctx context.Context) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getPendingReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.InterviewDate,
			&i.OfferDate,
			&i.Notes,
			&i.SalaryOffer,
			&i.ReminderSent,
			&i.FollowUpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingInterviews = `-- name: GetUpcomingInterviews :many
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE user_id = $1 
  AND interview_date IS NOT NULL 
  AND interview_date >= NOW()
  AND status = 'interviewing'
ORDER BY interview_date ASC
`

func (q *Queries) GetUpcomingInterviews(ctx context.Context, userID uuid.UUID) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingInterviews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.InterviewDate,
			&i.OfferDate,
			&i.Notes,
			&i.SalaryOffer,
			&i.ReminderSent,
			&i.FollowUpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserApplications = `-- name: GetUserApplications :many
SELECT id, user_id, job_id, status, applied_at, updated_at, 
       interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
FROM applications
WHERE user_id = $1
ORDER BY applied_at DESC
`

func (q *Queries) GetUserApplications(ctx context.Context, userID uuid.UUID) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getUserApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.UpdatedAt,
			&i.InterviewDate,
			&i.OfferDate,
			&i.Notes,
			&i.SalaryOffer,
			&i.ReminderSent,
			&i.FollowUpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE applications
SET reminder_sent = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markReminderSent, id)
	return err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET
  interview_date = COALESCE($2, interview_date),
  offer_date = COALESCE($3, offer_date),
  notes = COALESCE($4, notes),
  salary_offer = COALESCE($5, salary_offer),
  reminder_sent = COALESCE($6, reminder_sent),
  follow_up_date = COALESCE($7, follow_up_date),
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, job_id, status, applied_at, updated_at, 
          interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
`

type UpdateApplicationParams struct {
	ID            uuid.UUID      `json:"id"`
	InterviewDate sql.NullTime   `json:"interview_date"`
	OfferDate     sql.NullTime   `json:"offer_date"`
	Notes         sql.NullString `json:"notes"`
	SalaryOffer   sql.NullString `json:"salary_offer"`
	ReminderSent  sql.NullBool   `json:"reminder_sent"`
	FollowUpDate  sql.NullTime   `json:"follow_up_date"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplication,
		arg.ID,
		arg.InterviewDate,
		arg.OfferDate,
		arg.Notes,
		arg.SalaryOffer,
		arg.ReminderSent,
		arg.FollowUpDate,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.InterviewDate,
		&i.OfferDate,
		&i.Notes,
		&i.SalaryOffer,
		&i.ReminderSent,
		&i.FollowUpDate,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET
  status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, job_id, status, applied_at, updated_at, 
          interview_date, offer_date, notes, salary_offer, reminder_sent, follow_up_date
`

type UpdateApplicationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.ID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.InterviewDate,
		&i.OfferDate,
		&i.Notes,
		&i.SalaryOffer,
		&i.ReminderSent,
		&i.FollowUpDate,
	)
	return i, err
}
