// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*)
FROM jobs
WHERE 
  ($1::TEXT IS NULL OR title ILIKE '%' || $1::TEXT || '%')
  AND ($2::TEXT IS NULL OR company ILIKE '%' || $2::TEXT || '%')
  AND ($3::TEXT IS NULL OR location ILIKE '%' || $3::TEXT || '%')
  AND ($4::TEXT IS NULL OR source = $4::TEXT)
  AND ($5::BOOLEAN IS NULL OR is_active = $5::BOOLEAN)
`

type CountJobsParams struct {
	Title    sql.NullString `json:"title"`
	Company  sql.NullString `json:"company"`
	Location sql.NullString `json:"location"`
	Source   sql.NullString `json:"source"`
	IsActive sql.NullBool   `json:"is_active"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobs,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Source,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  title, 
  company, 
  location, 
  description, 
  salary_range, 
  requirements, 
  source, 
  link, 
  posted_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, company, location, description, salary_range, requirements, 
          source, link, posted_date, scraped_at, is_active, created_at, updated_at
`

type CreateJobParams struct {
	Title        string         `json:"title"`
	Company      string         `json:"company"`
	Location     string         `json:"location"`
	Description  string         `json:"description"`
	SalaryRange  sql.NullString `json:"salary_range"`
	Requirements sql.NullString `json:"requirements"`
	Source       string         `json:"source"`
	Link         string         `json:"link"`
	PostedDate   time.Time      `json:"posted_date"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Description,
		arg.SalaryRange,
		arg.Requirements,
		arg.Source,
		arg.Link,
		arg.PostedDate,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.SalaryRange,
		&i.Requirements,
		&i.Source,
		&i.Link,
		&i.PostedDate,
		&i.ScrapedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, title, company, location, description, salary_range, requirements, 
       source, link, posted_date, scraped_at, is_active, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.SalaryRange,
		&i.Requirements,
		&i.Source,
		&i.Link,
		&i.PostedDate,
		&i.ScrapedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByLink = `-- name: GetJobByLink :one
SELECT id, title, company, location, description, salary_range, requirements, 
       source, link, posted_date, scraped_at, is_active, created_at, updated_at
FROM jobs
WHERE link = $1
`

func (q *Queries) GetJobByLink(ctx context.Context, link string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByLink, link)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.SalaryRange,
		&i.Requirements,
		&i.Source,
		&i.Link,
		&i.PostedDate,
		&i.ScrapedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, company, location, description, salary_range, requirements, 
       source, link, posted_date, scraped_at, is_active, created_at, updated_at
FROM jobs
WHERE 
  ($3::TEXT IS NULL OR title ILIKE '%' || $3::TEXT || '%')
  AND ($4::TEXT IS NULL OR company ILIKE '%' || $4::TEXT || '%')
  AND ($5::TEXT IS NULL OR location ILIKE '%' || $5::TEXT || '%')
  AND ($6::TEXT IS NULL OR source = $6::TEXT)
  AND ($7::BOOLEAN IS NULL OR is_active = $7::BOOLEAN)
ORDER BY posted_date DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
	Title    sql.NullString `json:"title"`
	Company  sql.NullString `json:"company"`
	Location sql.NullString `json:"location"`
	Source   sql.NullString `json:"source"`
	IsActive sql.NullBool   `json:"is_active"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs,
		arg.Limit,
		arg.Offset,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Source,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Description,
			&i.SalaryRange,
			&i.Requirements,
			&i.Source,
			&i.Link,
			&i.PostedDate,
			&i.ScrapedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET
  title = COALESCE($2, title),
  company = COALESCE($3, company),
  location = COALESCE($4, location),
  description = COALESCE($5, description),
  salary_range = COALESCE($6, salary_range),
  requirements = COALESCE($7, requirements),
  source = COALESCE($8, source),
  link = COALESCE($9, link),
  is_active = COALESCE($10, is_active),
  posted_date = COALESCE($11, posted_date),
  updated_at = NOW()
WHERE id = $1
RETURNING id, title, company, location, description, salary_range, requirements, 
          source, link, posted_date, scraped_at, is_active, created_at, updated_at
`

type UpdateJobParams struct {
	ID           uuid.UUID      `json:"id"`
	Title        sql.NullString `json:"title"`
	Company      sql.NullString `json:"company"`
	Location     sql.NullString `json:"location"`
	Description  sql.NullString `json:"description"`
	SalaryRange  sql.NullString `json:"salary_range"`
	Requirements sql.NullString `json:"requirements"`
	Source       sql.NullString `json:"source"`
	Link         sql.NullString `json:"link"`
	IsActive     sql.NullBool   `json:"is_active"`
	PostedDate   sql.NullTime   `json:"posted_date"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Description,
		arg.SalaryRange,
		arg.Requirements,
		arg.Source,
		arg.Link,
		arg.IsActive,
		arg.PostedDate,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Description,
		&i.SalaryRange,
		&i.Requirements,
		&i.Source,
		&i.Link,
		&i.PostedDate,
		&i.ScrapedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
